curl -X "GET" "https://api.spotify.com/v1/search?q=Muse&type=track%2Cartist&market=US&limit=10&offset=5" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer BQCSFgnjbtieZUVwrZQXCB-cq2nUCrasDvtR6nBn7aKv3e0sURPo7zJd04ED85YX7RS8ix4m2qtbYk9GK6vBRs0oCF65wFfPG13CyAh1PNMbnpxFX5yT1tF4MLNQCE8Mq_eKUKUUrZ4NyIZBBSR2TEKbXkpatM2M_ifFS41BRniWCMmg2n3_o1y2GbF6"